version: '3'
services:
  notification-service:
    build: .
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example