version: '3'
services:
  notification-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notificationservice

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"